### PR TITLE
Issue #74 follow up messages

### PR DESCRIPTION
**Pull request by hd719**
Hey @schneidmaster !  For issue #74. 

So even w/ StackOver Flow I could not find out why the captcha was blacked out, but I am hoping what I have added to the ` app/views/repositories/submitted.erb` does work. 

If the code does not work, please do let me know and I will try to fix it. 

-Thank you.

### CODE REVIEW

**Comment by schneidmaster** [comment]
Looks pretty good, a couple of comments:

* Could you revert the schema changes, they don't seem to do anything (other than that your schema was probably generated from a newer version of Rails) and I'd prefer to keep the PR to one issue at a time
* I think we should have this disabled by default and enabled via a configuration option. Currently, all of the copy on the site is either user-configurable or draws from the [locales](https://github.com/schneidmaster/gitreports.com/tree/master/config/locales) -- a few users have submitted translations. Obviously I don't know how to translate the new copy from English, but for their setups, I don't want to start displaying some non-translated English by default.
* Finally, should add a test [here](https://github.com/schneidmaster/gitreports.com/blob/master/spec/features/repositories_feature_spec.rb#L188) for the new code.

**Comment by hd719** [comment]
@schneidmaster Cool! 

Just a quick question, what do you mean by this 

```
I think we should have this disabled by default and enabled via a configuration option. Currently, all of the copy on the site is either user-configurable or draws from the locales -- a few users have submitted translations. Obviously I don't know how to translate the new copy from English, but for their setups, I don't want to start displaying some non-translated English by default.
```

-Thank you. 

Also I will revert the schema to how it was before.

**Comment by schneidmaster** [comment]
I think that by default, we should not show the issue link, and add a configuration option to the `Repository` model to allow users to turn on the issue link via a checkbox. Locales are something used by Rails to support translations of text in the application -- currently, all of the text in the app either uses locales (with some users using French and Polish) or is user-configurable (i.e. they type what they want in a form). So if we enable the issue link by default, users that are expecting the site to currently all be in French or Polish would suddenly see some English showing up when issues are submitted. Making it opt-in helps with that since we don't break current issue pages.

You should look in the `spec/features` folder for examples of existing feature tests.

**Comment by hd719** [comment]
Oh okay, I get what you are saying. So do you want me to take out the issue link? 

But in the meantime I will revert the schema and write a test for this feature.

**Comment by hd719** [comment]
Hey @schneidmaster is there a rails command to revert the schema back to how it was originally?

-THank you.

**Comment by hd719** [comment]
@schneidmaster Hey any update on this?

**Comment by schneidmaster** [comment]
@hd719 your test command is incorrect -- you need to be in the project root and run `rspec spec/features/repositories_feature_spec.rb`

**Comment by hd719** [comment]
@schneidmaster Hey so I am having trouble with writing out the tests, I understand the test should go under `describe submit issue`, but where it would it go exactly?

**Comment by schneidmaster** [comment]
You can't do `expect_to visit ...` -- `visit` is a command that tells Capybara to visit the provided URL. If you're trying to test that the page is on a particular URL you're looking for `expect(page).to have_current_path(whatever_path)`

**Comment by hd719** [comment]
Hey @schneidmaster I added the new path that test's for the `here` button that should link to the owners repository issue, but for some reason it is not passing. 

- Thank you.

**Comment by hd719** [comment]
Hey @schneidmaster sorry for the bother, but any update with this I would really like to get this PR merged soon. 

I am currently in a coding bootcamp and we have to contribute to a set number of repos. and this one is currently on my list. 

P.S. By the way thank you all the help very much appreciated.

**Comment by schneidmaster** [comment]
Hey @hd719. Looks like this project is actually on an older version of Capybara, if you upgrade Capybara to >= 2.5 that syntax should work. 

As I said above, we'll also need to add a configuration option to the repository itself, to make this link opt-in for non-English users.

**Comment by hd719** [comment]
@schneidmaster Alright sounds good! I am going to try and add a configuration option so the link would work for non-English users. 

Real quick in order for me to do this, where should I start? Any advice would be appreciated. 

- Thanks again bro!

**Comment by schneidmaster** [comment]
`allow_issue_title` is a pretty good example -- it is a configuration option that allows users to set the issue title in GitHub, while your configuration option will be to show this link when the issue is submitted. Look at the files from [this search](https://github.com/schneidmaster/gitreports.com/search?utf8=%E2%9C%93&q=allow_issue_title&type=) to get an idea of where your option needs to be added.

**Comment by schneidmaster** [comment]
Closing this PR for now since it seems to have gone stale. Feel free to open a new PR if you decide to take this feature back up.

**Pull request closed without merging**
