### PR TITLE
Added polish translation

### PR DESCRIPTION
**Pull request by ad-m**
Hi,

I am from Poland. I am prepared polish translation for you software. 

Please merge and notify about deployment.

### CODE REVIEW

**Comment by ad-m** [comment]
I believe my commit are correct, but your tests don't support translation, so it are looking for non-translated text. I don't know ruby enough to fix that, but I can help in python any way.

**Comment by schneidmaster** [comment]
Yeah I noticed that, I am fixing the tests now.

**Comment by schneidmaster** [comment]
I have fixed the tests but there is also an error in your code. The first line of `config/locales/pl.yml` should be `pl:` not `en:`. Please fix and I will merge.

**Comment by schneidmaster** [comment]
Deploying, code should be live in a minute or two.

**Pull request merged**
